# Generated by Django 5.1.5 on 2025-02-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
